spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 839676929970068
            client-secret: b5c16f524008692163d7c926079bf3cd
            scope:
              - email
              - public_profile
app:
  auth:
    tokenSecret: javainuse
    tokenExpirationMsec: 5*60*60*1000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:8081/oauth2/redirect